services:
  ollama-architect:
    image: ollama/ollama:latest 
    container_name: ollama-architect
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11435:11434"

  ollama-pull-model:
    image: curlimages/curl:latest
    container_name: ollama-pull-model
    depends_on:
      - ollama-architect
    entrypoint: [ "sh", "-c", "sleep 5 && curl -X POST http://ollama-architect:11434/api/pull -d '{\"model\": \"llama3\"}'" ]

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-architect
    ports:
      - "8001:8000"
    volumes:
      - chroma_persistence:/chroma/data

  app:
    build: .
    container_name: vulnerable-rag-app
    volumes:
      - .:/app
      - chroma_persistence:/app/chroma_data
    depends_on:
      - ollama-architect
      - chromadb
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama-architect:11434
      - CHROMA_HOST=chromadb-architect

volumes:
  chroma_persistence: